name: CI

env:
  COMPOSE_INTERACTIVE_NO_CLI: 1

on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  pest:
    name: Tests (Pest)
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install composer dependencies
      run: composer install
    - name: Run tests
      run: vendor/bin/pest
